### ISSUE TITLE
Review comments do not appear in the submitted page

### ISSUE THREAD

**Issue by faith-mutua** [onaio/kaznet-frontend#260]
**Expected behavior**

Review comments should also be displayed in the **Submitted** page on the mobile app once a submission has been reviewed. 

**Actual behavior**
No review comments are being displayed on the **Submitted** page. Only the default comment "Data submitted from the wrong location" is usually shown in a blue mailbox. 

**Steps to reproduce**
- Submit a task. 
- Review the task in kaznet.ona.io and add a review comment. 
- Check the **Submitted** page on the mobile app once it has been updated.

**Comment by akahure** [comment]
This has been resolved
